# Generated by Django 4.2.27 on 2026-06-03 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('pickup_time', models.CharField(max_length=40)),
                ('pickup_days', models.CharField(max_length=40)),
                ('schedule', models.CharField(max_length=120)),
                ('image', models.URLField(max_length=500)),
                ('bio', models.TextField()),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'confirmed')], default='confirmed', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('meals_per_week', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('filter_keys', models.JSONField(default=list)),
                ('image', models.URLField(max_length=500)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.cook')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id_slug', models.CharField(max_length=40)),
                ('plan_name', models.CharField(max_length=200)),
                ('cook_id_slug', models.CharField(max_length=40)),
                ('cook_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meals_per_week', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('pickup_days', models.CharField(blank=True, max_length=40)),
                ('pickup_time', models.CharField(blank=True, max_length=40)),
                ('payment_last4', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('active', 'active'), ('skipped', 'skipped'), ('cancelled', 'cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cook')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.weeklyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.cook')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('cook_name', models.CharField(max_length=120)),
                ('cook_id_slug', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qty', models.PositiveSmallIntegerField()),
                ('image', models.URLField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.mealorder')),
            ],
        ),
        migrations.CreateModel(
            name='CookApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('specialty', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.SlugField(max_length=60)),
                ('day', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icon', models.CharField(default='Utensils', max_length=20)),
                ('image', models.URLField(max_length=500)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.cook')),
            ],
            options={
                'ordering': ['item_id'],
                'unique_together': {('cook', 'item_id')},
            },
        ),
    ]
